/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lessons */
        get: operations["list_lessons_api_v1_admin_lessons_get"];
        put?: never;
        /**
         * Create Lesson
         * @description Validate, store the audio, create the lesson in `processing`, enqueue ingestion (AC-M2-01, 02.1).
         */
        post: operations["create_lesson_api_v1_admin_lessons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson */
        get: operations["get_lesson_api_v1_admin_lessons__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Lesson */
        patch: operations["update_lesson_api_v1_admin_lessons__lesson_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/lessons/{lesson_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Lesson */
        post: operations["publish_lesson_api_v1_admin_lessons__lesson_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/lessons/{lesson_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Lesson */
        post: operations["retry_lesson_api_v1_admin_lessons__lesson_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/lessons/{lesson_id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unpublish Lesson */
        post: operations["unpublish_lesson_api_v1_admin_lessons__lesson_id__unpublish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/segments/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Segments */
        post: operations["merge_segments_api_v1_admin_segments_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Segment */
        patch: operations["update_segment_api_v1_admin_segments__segment_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/segments/{segment_id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Split Segment */
        post: operations["split_segment_api_v1_admin_segments__segment_id__split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Config
         * @description Which sign-in methods the login page should show.
         */
        get: operations["auth_config_api_v1_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Callback
         * @description Any failure (cancelled, bad state, Google error) → /login with an error; no user is created.
         */
        get: operations["google_callback_api_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Start */
        get: operations["google_start_api_v1_auth_google_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Magic Link
         * @description Same response whether or not the email has an account (no account enumeration, AC-M1-02.1).
         */
        post: operations["request_magic_link_api_v1_auth_magic_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/magic-link/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Magic Link
         * @description Read-only check used by the confirmation page. Link scanners that fetch the emailed URL (a web page)
         *     never reach the consuming POST below, so they cannot burn the single-use link.
         */
        get: operations["preview_magic_link_api_v1_auth_magic_link_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/magic-link/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Magic Link */
        post: operations["verify_magic_link_api_v1_auth_magic_link_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness + database reachability. Returns 503 when Postgres is unreachable.
         */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description Deletes the user; sessions (and later progress/vocab) go with it via ON DELETE CASCADE.
         */
        delete: operations["delete_me_api_v1_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_me_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthConfig */
        AuthConfig: {
            /** Google Enabled */
            google_enabled: boolean;
            /** Magic Link Enabled */
            magic_link_enabled: boolean;
        };
        /** Body_create_lesson_api_v1_admin_lessons_post */
        Body_create_lesson_api_v1_admin_lessons_post: {
            /** Audio */
            audio: string;
            /**
             * Level
             * @enum {string}
             */
            level: "beginner" | "intermediate" | "advanced";
            /** License */
            license: string;
            /** Source Name */
            source_name: string;
            /**
             * Source Url
             * @default
             */
            source_url: string | "";
            /** Title */
            title: string;
            /**
             * Topic
             * @enum {string}
             */
            topic: "talk" | "news" | "interview" | "conversation";
            /** Transcript */
            transcript: string;
        };
        /** DeleteAccount */
        DeleteAccount: {
            /** Confirm Email */
            confirm_email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Db */
            db: string;
            /** Status */
            status: string;
        };
        /** LessonDetail */
        LessonDetail: {
            /** Attention Count */
            attention_count: number;
            /** Audio Url */
            audio_url: string;
            /** Duration Ms */
            duration_ms: number;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: number;
            /** Level */
            level: string;
            /** License */
            license: string;
            /** Published At */
            published_at: string | null;
            /** Segment Count */
            segment_count: number;
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /** Slug */
            slug: string;
            /** Source Name */
            source_name: string;
            /** Source Url */
            source_url: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Topic */
            topic: string;
            /** Transcript */
            transcript: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LessonSummary */
        LessonSummary: {
            /** Attention Count */
            attention_count: number;
            /** Duration Ms */
            duration_ms: number;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: number;
            /** Level */
            level: string;
            /** Published At */
            published_at: string | null;
            /** Segment Count */
            segment_count: number;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Topic */
            topic: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LessonUpdate */
        LessonUpdate: {
            /** Level */
            level?: ("beginner" | "intermediate" | "advanced") | null;
            /** License */
            license?: string | null;
            /** Source Name */
            source_name?: string | null;
            /** Source Url */
            source_url?: string | "" | null;
            /** Title */
            title?: string | null;
            /** Topic */
            topic?: ("talk" | "news" | "interview" | "conversation") | null;
        };
        /** MagicLinkAccepted */
        MagicLinkAccepted: {
            /** Message */
            message: string;
        };
        /** MagicLinkPreview */
        MagicLinkPreview: {
            /** Email */
            email: string;
        };
        /** MagicLinkRequest */
        MagicLinkRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Return To
             * @default /
             */
            return_to: string;
        };
        /** MagicLinkToken */
        MagicLinkToken: {
            /** Token */
            token: string;
        };
        /** Me */
        Me: {
            /**
             * Csrf Token
             * @description Send back as X-CSRF-Token on state-changing requests
             */
            csrf_token: string;
            /** Email */
            email: string;
            /** Email Reminder */
            email_reminder: boolean;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Playback Rate Default */
            playback_rate_default: number;
            /**
             * Reminder Time
             * Format: time
             */
            reminder_time: string;
            /** Role */
            role: string;
            /** Strict Punct Default */
            strict_punct_default: boolean;
            /** Timezone */
            timezone: string;
        };
        /** MeUpdate */
        MeUpdate: {
            /** Email Reminder */
            email_reminder?: boolean | null;
            /** Name */
            name?: string | null;
            /** Playback Rate Default */
            playback_rate_default?: number | null;
            /** Reminder Time */
            reminder_time?: string | null;
            /** Strict Punct Default */
            strict_punct_default?: boolean | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** MergeRequest */
        MergeRequest: {
            /** First Id */
            first_id: number;
            /** Second Id */
            second_id: number;
        };
        /** SegmentOut */
        SegmentOut: {
            /** Attention Reason */
            attention_reason: string;
            /** End Ms */
            end_ms: number;
            /** Id */
            id: number;
            /** Idx */
            idx: number;
            /** Needs Attention */
            needs_attention: boolean;
            /** Start Ms */
            start_ms: number;
            /** Text */
            text: string;
            /** Translation Vi */
            translation_vi: string;
            /**
             * Word Count Aligned
             * @description Word timings still match the text (split can derive the time)
             */
            word_count_aligned: boolean;
        };
        /** SegmentUpdate */
        SegmentUpdate: {
            /** End Ms */
            end_ms?: number | null;
            /** Start Ms */
            start_ms?: number | null;
            /** Text */
            text?: string | null;
            /** Translation Vi */
            translation_vi?: string | null;
        };
        /** SignedIn */
        SignedIn: {
            /** Return To */
            return_to: string;
        };
        /** SplitRequest */
        SplitRequest: {
            /** Split Ms */
            split_ms?: number | null;
            /** Word Index */
            word_index: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_lessons_api_v1_admin_lessons_get: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lesson_api_v1_admin_lessons_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_lesson_api_v1_admin_lessons_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_api_v1_admin_lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                lesson_id: number;
            };
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lesson_api_v1_admin_lessons__lesson_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                lesson_id: number;
            };
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_lesson_api_v1_admin_lessons__lesson_id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                lesson_id: number;
            };
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_lesson_api_v1_admin_lessons__lesson_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                lesson_id: number;
            };
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpublish_lesson_api_v1_admin_lessons__lesson_id__unpublish_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                lesson_id: number;
            };
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_segments_api_v1_admin_segments_merge_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_segment_api_v1_admin_segments__segment_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                segment_id: number;
            };
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_segment_api_v1_admin_segments__segment_id__split_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                segment_id: number;
            };
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_config_api_v1_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
        };
    };
    google_callback_api_v1_auth_google_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                oauth_state?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_start_api_v1_auth_google_start_get: {
        parameters: {
            query?: {
                return_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_magic_link_api_v1_auth_magic_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagicLinkAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_magic_link_api_v1_auth_magic_link_preview_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagicLinkPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_magic_link_api_v1_auth_magic_link_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkToken"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedIn"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccount"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: {
                sid?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
